server:
  port: ${PORT:${SERVICE_PORT:0}}

spring:
  data:
    mongodb:
      uri: mongodb+srv://dbuser:Passw0rd11235@cluster0.abvys.mongodb.net/SavingAccountDB?retryWrites=true&w=majority

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url.default-zone: http://localhost:8761/eureka

constans:
  url:
    server: http://localhost:8080